version: '3.2'

services:
  tor-browser:
    image: dperson/torproxy
    container_name: scraper-tor-browser
    ports:
      - '9001:9001'
      - '9051:9051'
    networks:
      - webappnetwork
  web:
    container_name: scrapeServiceProvider
    build: .
    depends_on:
      - tor-browser
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
